config/routes.rb
GoldenSeven::Application.routes.draw do
  root :to => 'Pictures#index'

  get '/pictures/new' => 'Pictures#new', :as => 'new_picture'
  post '/pictures' => 'Pictures#create', :as => 'pictures'

  get '/pictures' => 'Pictures#index', :as => 'pictures'
  get '/pictures/:id' => 'Pictures#show', :as => 'picture'

  get '/pictures/:id/edit' => 'Pictures#edit', :as => 'edit_picture'
  put '/pictures/:id' => 'Pictures#update', :as => 'picture'

  delete '/pictures/:id' => 'Pictures#destroy', :as => 'picture'
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :source, :caption
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find_by_id(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    picture = Picture.new(params[:picture])
    picture.save

    redirect_to pictures_url
  end

  def edit
    @picture = Picture.find_by_id(params[:id])
  end

  def update
    picture = Picture.find_by_id(params[:id])
    picture.update_attributes(params[:picture])

    redirect_to picture_url(picture)
  end

  def destroy
    picture = Picture.find_by_id(params[:id])
    picture.destroy

    redirect_to pictures_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoldenSeven</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>

<nav>
  <%= link_to "Cancel", @picture %>
</nav>

<%= form_for @picture do |f| %>
  <%= f.text_field :source %>
  <%= f.text_field :caption %>
  <%= submit_tag %>
<% end %>

app/views/pictures/index.html.erb
<h1>List of Pictures</h1>

<nav>
  <%= link_to "Add A New Picture", new_picture_url %>
</nav>

<ul>
  <% @pictures.each do |picture| %>
    <li>
      <%= image_tag picture.source, width: 240 %>
      <p><%= picture.caption %></p>
      <nav>
        <%= link_to "Show", picture %>
        <%= link_to "Edit", edit_picture_url(picture) %>
        <%= link_to "Delete", picture, :method => 'delete' %>
      </nav>
    </li>
  <% end %>
</ul>

app/views/pictures/new.html.erb
<h1>Add A New Picture</h1>

<nav>
  <%= link_to "Cancel", pictures_url %>
</nav>

<%= form_for @picture do |f| %>
  <%= f.text_field :source %>
  <%= f.text_field :caption %>
  <%= f.submit %>
<% end %>

app/views/pictures/show.html.erb
<h1>Picture Details #<%= @picture.id %></h1>

<nav>
  <%= link_to "Edit", edit_picture_url(@picture) %>
  <%= link_to "Back", pictures_url %>
</nav>

<%= image_tag @picture.source, width: 240 %>
<p><%= @picture.source %></p>
<p><%= @picture.caption %></p>